### ISSUE TITLE
Images in article not constrained 

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/Hinduism-Today#1]
http://45.56.91.98/modules/smartsection/item.php?itemid=5792

see 

https://www.hinduismtoday.com/modules/smartsection/item.php?itemid=5792

<p class="image"><img src="/archives/2017/7-9/images/f0020-01.jpg" alt="Image"/></p>

Its the same HTML  in back place, so it CSS problem for images needs to by constrained to fit the pages.

**Comment by Brahmanathaswami** [comment]
If you have a choice use "object-fit:scale-down;"

**Comment by mambax7** [comment]
it's fixed now: http://45.56.91.98/modules/smartsection/item.php?itemid=5792
