### ISSUE TITLE
Search Icon IS Missing

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/Hinduism-Today#10]
![2018-08-30_07-58-36](https://user-images.githubusercontent.com/3675722/44874758-efbb2c00-ac37-11e8-8a98-88261a3afa9e.png)

It should look like this:

![2018-08-30_07-58-31](https://user-images.githubusercontent.com/3675722/44874886-432d7a00-ac38-11e8-8875-8ac67d66674f.png)

**Comment by mambax7** [comment]
That should go to whoever changed the theme...
