### ISSUE TITLE
RSS Feed Is Faling

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/Hinduism-Today#12]
The RSS feed URL registered with Feedblitz fails on the new server

https://www.hinduismtoday.com/blogs-news/feed,0.rss

XML Parsing Error: no root element found
Location: https://www.hinduismtoday.com/blogs-news/feed,0.rss
Line Number 1, Column 1:

You can change to whatever it need to be.

**Comment by Brahmanathaswami** [comment]
hopefully we can get this settled tonite.

**Comment by Brahmanathaswami** [comment]
Obviously, the RSS feed URL can be "anything" ... just in case to .htaccess re-writes by our dear crazy friend in Australia, can be (Should Be!) deprecated.

**Comment by Brahmanathaswami** [comment]
The .htaccess file in the new server is a way old versions. We have a version from 4. 2018 and prior that Aug 30 2017.

the latest version on the new server doesn't make sense -- modified. 2/19/2016,, where is that from?

**Comment by Brahmanathaswami** [comment]
The rewrite full  from 4.2018 is


RewriteRule ^blogs-news/feed,([0-9]+).rss 																		modules/xnews/backendt.php?topicid=$2

**Comment by mambax7** [comment]
I'm looking into it....

**Comment by Brahmanathaswami** [comment]
the "backendt.php" file there is a different between the old on and new on. on line 148, the function: $tmp-append
is set to be array (in the old file that worked) 
`$tpl->append('items', array(
                'title' => XoopsLocal::convert_encoding(htmlspecialchars($storytitle, ENT_QUOTES)) ,
                'link' => nw_seo_UrlGenerator(_MA_NW_SEO_ARTICLES, $story->storyid(), $item_title) ,
                'guid' => $story->nw_stripeKey(md5($story->title().$story->topic_title), 7, 32),
				'category' => XoopsLocal::convert_encoding(htmlspecialchars($story->topic_title, ENT_QUOTES)) ,
                'pubdate' => formatTimestamp($story->published(), 'rss') ,
                'description' => $description));`

Array is missing in the new files.

`$tpl->append('items', [
                'title' => XoopsLocal::convert_encoding(htmlspecialchars($storytitle, ENT_QUOTES)) ,
                'link' => nw_seo_UrlGenerator(_MA_NW_SEO_ARTICLES, $story->storyid(), $item_title) ,
                'guid' => $story->nw_stripeKey(md5($story->title().$story->topic_title), 7, 32),
				'category' => XoopsLocal::convert_encoding(htmlspecialchars($story->topic_title, ENT_QUOTES)) ,
                'pubdate' => formatTimestamp($story->published(), 'rss') ,
                'description' => $description
            ]); `

**Comment by Brahmanathaswami** [comment]
I won't change anything, just 'investigating"  to help you.

**Comment by Brahmanathaswami** [comment]
Have to shut down for the day. I will look for a new RSS feed in the morning, or if you get the old one work, feedblitz catch it  and will "fire" the HPI news as usuall.

**Comment by mambax7** [comment]
OK, I'll keep you posted what I find out...

**Comment by mambax7** [comment]
It should be fixed now.
