### ISSUE TITLE
Downloads Module - Permissions Problem? Can't upload new record

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/Hinduism-Today#13]
It my duty to upload the PDF, Epub and Mobi for Kindle.
I do this in the Download Module

* go to Download
* Add Category - October/November/Decemeber 2018
* Save it with weight 737. for this issue
  * it is saved. I see in PHP admin which I have open
* Set category Permission and weight... 
  * error "You do not have permission to access this area"

--
* try add an new download record fill in the title 
  * October/November/December 2018 Kindle. and information
  * give it the new category
* Save

That record is not saved. I check in PHP My admin. there is no new records saved.

Normally, in the past, the record is saved, but I may not have set permission for the category.  So I don't see in the UI it set permissions for the category. 

Now, am block from creating  a new records,

![2018-09-12_09-53-28](https://user-images.githubusercontent.com/3675722/45450362-b640e280-b673-11e8-8e54-3c1551a853cc.png)

**Comment by Brahmanathaswami** [comment]
There is will be a lot of activity in these few day. uploading new record for the latest issue. Maybe the above need fixing (change folder perms to 777)

**Comment by mambax7** [comment]
the folder permissions have been fixed

reg. the category permissions, please set them currently directly in the category, it works. 
I'll look into why it is not accepting from within the Permissions tab

**Comment by Brahmanathaswami** [comment]
OK, did that. At this point perms for the category are, in and correct. Settings perms from the Permisson tab is not a big issue. Bigger is: Cannot upload new records in the download module. Even though

 * I am web master
 * upload for web master is approved for this category.

New Download --> fill in record -- Submit 

Screen goes back to index, nothing happens, no error msg either, 

I still see the last download for July. Also look at table for phpmyadmin, no records were added.

**Comment by Brahmanathaswami** [comment]
Apparently this is not a global issue. Yesterday they successfully created records in the Smart Section module for the articles of the Oct edition, so, this may narrow the search -- the problem in just the Downloads module...
