### ISSUE TITLE
XOOPS Favicon instead of HToday

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/Hinduism-Today#14]
I’m now seeing the Xoops default favicon on all my browsers. I replaced is several days ago and did cache clearing to no avail.

I changed it in these places:

/public_html/favicon.ico

And 

public_html/themes/SuryaBlue03/images/favicon.png

Not sure which one it uses, but in theory they should be displaying our HT logo using one of them. Is there another place that the favicon exists?

**Comment by mambax7** [comment]
Fixed
