### ISSUE TITLE
Test Out HPI Desktop to New IP

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/Hinduism-Today#4]
- [x] Michael: say that go ahead to for test
- [x] BR: change absolute url the IP in desk client
- [x] BR: send some drafts (no do publish!) the see then get in record dBase
- [x] BR: Test some html in a draft.
- [ ] BR: temporarily sent feedblitz to manually publish instead a daily a midnight
- [ ] BR: switch IP feed for the rss to the next set
- [ ] BR: test again

**Comment by Brahmanathaswami** [comment]
We have test for this ip Name we get an error from XOOPS saying 

story={%22usernamehttps://www.himalayanacademy.com%5C%22%3ESource%3C/a%3E%3Cbr/%3E%3Cbr/%3EWe%20have%20good%20news.%20Water%20has%20memory.%3Cbr%20/%3E%22,%22topicid%22:%20%222%22,%22title%22:%20%22Water%20Has%20Memory%22,%22published%22:%20%220%22}}

{"ErrNum":9,"ErrDesc":"No Permission for plug-in"}

**Comment by mambax7** [comment]
please don't place usernames and passwords here :) 
I'll be looking at this today...

**Comment by Brahmanathaswami** [comment]
YIkes! I edited them out.

**Comment by mambax7** [comment]
The first four tests are working now OK
