### ISSUE TITLE
Tag is Inside Section is Wrong

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/Hinduism-Today#7]
Click on
Education
    All Past Education Features

It take you have to a listing of Publishes Desk!

see what if should go:

https://www.hinduismtoday.com/modules/tag/desk.tag.php/Insight

**Comment by mambax7** [comment]
Seems to me that the results are the same, there is only discrepancy in the database, i.e.  the original site has logically articles beyond Sept. 2017, and there are more hits, but once you compare the existing data in both sites, then it look OK. 
I'm closing it, but please re-open if you feel, it's about something else....
![image](https://user-images.githubusercontent.com/613686/39080063-43099400-44f5-11e8-8b71-df6f42bb2bc0.png)
