### ISSUE TITLE
Cannot Post to /modules/XJson

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/Hinduism-Today#9]
Well first test failed (as i suspected) 

can  you examine the code for the old modules/xjson and compare with new one? Perhaps Simon or Andre hacked it. And we don't have their patches on the new server.

The latest XOOPS  gave us this message:

" <p class='xo-siteblocked-desc'>Error : ArgumentCountError: Too few arguments to function XoopsModules\Xjson\FunctionsHandler::__construct(), 0 passed in /home/htoday/public_html/modules/xjson/include/server.php on line 36 and exactly 1 expected</p>

**Comment by mambax7** [comment]
OK, I'll look into it.

**Comment by Brahmanathaswami** [comment]
If REST XML POST Json api are "not your thing" I can get Andre to look at it, he is a wizard. So don't struggle with it in it not obvious it you.

**Comment by Brahmanathaswami** [comment]
Any movement on this

**Comment by mambax7** [comment]
Looking at this as we speak....

**Comment by mambax7** [comment]
It seems to be PHP 7 migration issue:
http://php.net/manual/en/migration71.incompatible.php
Let me see how to fix that...

**Comment by Brahmanathaswami** [comment]
Try to change the file  in line 10:
 
 /**
 * FunctionsHandler constructor.
 * @param null|string $wsdl
 */
public function __construct($wsdl = null)
{
}
That should (hopefully) work.
 
This was related to the "Throw on passing too few function arguments" in PHP 7.1:
 
http://php.net/manual/en/migration71.incompatible.php
 
 
Can you email me exactly the procedure that you use, so I could test issues locally here?
 
Michae

**Comment by Brahmanathaswami** [comment]
Thank you for the R & D,  We can fix it, (unless on want to learn a new language "Livecode" which it make great stride the "teach children how to code" world (see. https://livecode.org/)

But I think you have enough to do. I am assigned this to myself.

**Comment by mambax7** [comment]
I've fixed that on your server. Please test it if it made a difference.

**Comment by Brahmanathaswami** [comment]
Well progress? "sort of"  now we have a new error:

{"ErrNum":9,"ErrDesc":"No Permission for plug-in"}

**Comment by Brahmanathaswami** [comment]
I have used on the test site a newer version from Wishcraft that has some changes to the code.
 
Unfortunately, Wishcraft used the error message:
{"ErrNum":9,"ErrDesc":"No Permission for plug-in"}

all over the place, so I am not sure from which exactly location it was coming from.
 
So right now I am trying to figure out if this is what is causing the problem, or something else on the server itself.
 
I've changed right now the installation of xjson to the same one you have on the original server.
 
Could you please test it if it works? If it does, then I'll leave it there, just fix all the issues related to PHP 7.

**Comment by Brahmanathaswami** [comment]
I get a "site blocked" page:

<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Strict//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd'>
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=utf-8;charset=utf-8' />
<title>Internal server error</title>
<style type='text/css'>
* { margin: 0; padding: 0; font-family: Arial, Helvetica, sans-serif;}
body {font-size: 12px; background-color: #f0f0f0;

}
#xo-siteblocked {
    border: 1px solid #c0c4c0;
    width: 375px;
    height: 318px;
    margin: 150px auto;
    text-align: center;
    background-color: #fff;
    background-image: url(http://45.56.91.98/images/img_errors.png);
    background-repeat: no-repeat;
    background-position: 30px 50px;
    padding-left: 300px;
    padding-right: 30px;
    border-radius: 15px;
        -moz-border-radius: 15px;
        -webkit-border-radius: 15px;
}
 #xo-siteblocked h1 {font-size: 1.7em; margin: 45px 0 30px 0;}
 #xo-siteblocked h2 {font-size: 1.5em; margin: 0 0 30px 0;}
 #xo-siteblocked h1, h2 {font-weight: normal; text-shadow: 1px 1px 2px #ccc;}
 #xo-siteblocked a,  #xo-siteblocked a:visited {color: #2cb0ff; text-decoration: none;}
 #xo-siteblocked p { font-size: 1.3em; margin-top: 12px; line-height: 2em;}
 #xo-siteblocked p.xo-siteblocked-message { height: 70px;}
 #xo-siteblocked p.xo-siteblocked-desc { font-size: .9em; font-style: italic; margin-top: 25px;}
</style>
</head>
<body>
    <div id='xo-siteblocked'>
        <h1>A problem has occurred on our server!</h1>
        <h2>Page is currently unavailable</h2>
        <p class='xo-siteblocked-message'>We are working on a fix<br><a href='/'>Please come back soon ...</a></p>
        <p class='xo-siteblocked-desc'>Error : ArgumentCountError: Too few arguments to function FunctionsHandler::__construct(), 0 passed in /home/htoday/public_html/modules/xjson/include/server.php on line 11 and exactly 1 expected</p>
    </div>
</body>
</html><div style='color:#f0f0f0;background-color:#f0f0f0;'>Backtrace:<br></div>

**Comment by mambax7** [comment]
Please try again. I think it was related to the fact that the program is using eval() function, and some of the plugins got removed the closing "?>" tags, but they were needed for the eval() function.  Let's see if this works now....

**Comment by Brahmanathaswami** [comment]
Got this response for line 12.

   <div id='xo-siteblocked'>
        <h1>A problem has occurred on our server!</h1>
        <h2>Page is currently unavailable</h2>
        <p class='xo-siteblocked-message'>We are working on a fix<br><a href='/'>Please come back soon ...</a></p>
        <p class='xo-siteblocked-desc'>Error : ArgumentCountError: Too few arguments to function FunctionsHandler::__construct(), 0 passed in /home/htoday/public_html/modules/xjson/include/server.php on line 12 and exactly 1 expected</p>
    </div>

**Comment by mambax7** [comment]
It's fixed now
